import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Container from "./components/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
          <Navbar/>
        <Container>
          {children}
        </Container>
      
        
      </body>
    </html>
  );
}
